apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pyp0m9rxh-nodejs
  janus-idp.io/tekton: pyp0m9rxh-nodejs
  backstage.io/kubernetes-id: pyp0m9rxh-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pyp0m9rxh-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
